### ISSUE TITLE
Support for 'K' and 'M' suffixes for integer constants

### ISSUE THREAD

**Issue by nebularnoise** [pftbest/ldparser#2]
I've successfully used this parser with linkerscript that define constants in hex format, but it will fail with an equivalent 'human-readable' text format.

>  Additionally the suffixes K and M may be used to scale a constant by respectively. For example, the following all refer to the same quantity:
>
>        _fourk_1 = 4K;
 >       _fourk_2 = 4096;
 >       _fourk_3 = 0x1000;

source: https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_chapter/ld_3.html#SEC8

For reference, I was specifically using those in the MEMORY section, e.g.:
```
MEMORY
{
bootloader (rx) : ORIGIN = 0x08000000, LENGTH = 0x020000
FLASH (rx)     : ORIGIN = 0x08020000, LENGTH = 0xE0000
}
```
this will parse successfully

vs
```
MEMORY
{
bootloader (rx) : ORIGIN = 0x08000000, LENGTH = 128k
FLASH (rx)     : ORIGIN = 0x08020000, LENGTH = 1M - 128k
}
```
which won't

I will post minimum reproducible example later

**Comment by pftbest** [comment]
Hello. The K and M suffixes should work fine. I think in your example the problem is not the suffix but the expression with minus operation. My parser expects a single number here, it may be hard to add support for evaluating expressions. If I remember correctly in the other parts of the parser I just return expressions as is without evaluating them, so we don't have the code to evaluate results. I can do the same here and just return the expression but I'm not sure how useful that would be.

**Comment by nebularnoise** [comment]
You're absolutely right, I was mistaken. As soon as I removed the expressions, the error is gone.

Closing this issue
